### ISSUE TITLE
Elasticsearch 8 /info response object changed and this.esVersion is not set

### ISSUE THREAD

**Issue by gnanaprakash** [Milad/bunyan-elasticsearch-bulk#13]
Please find the /info response object, the version number path should be resp.version.number. Due to this you code check to find this.esVersion = 7 is failing. Please fix.  

{ name: 'ip-172-31-12-69', cluster_name: 'elasticsearch', cluster_uuid: '4sEVT3glTLaZ72F0kaLLxw', version: {… }, tagline: 'You Know, for Search' }
cluster_name: 'elasticsearch'
cluster_uuid: '4sEVT3glTLaZ72F0kaLLxw'
name: 'ip-172-31-12-69'
tagline: 'You Know, for Search'
**version: { number: '8.4.2', build_flavor: 'default', build_type: 'deb', build_hash:** '89f8c6d8429db93b816403ee75e5c270b43a940a', build_date: '2022-09-14T16:26:04.382547801Z', … }
}

**Comment by Milad** [comment]
Will check soon!

**Comment by Milad** [comment]
I couldn't reproduce such a problem!
