### ISSUE TITLE
Update elasticsearch library

### ISSUE THREAD

**Issue by zacepilin** [Milad/bunyan-elasticsearch-bulk#2]
Hello!
I run 'npm audit' and I see

│ Moderate      │ Prototype Pollution                                    
│ Package       │ lodash                                                       
│ Patched in    │ >=4.17.11                                                    
│ Path             │ bunyan-elasticsearch-bulk > elasticsearch >   lodash                                                       
│ More info      │ https://npmjs.com/advisories/782                             

│ Low              │ Prototype Pollution                                          
│ Package       │ lodash                                                       
│ Patched in    │ >=4.17.5                                                     
│ Path              │ bunyan-elasticsearch-bulk > elasticsearch >  lodash                                                       
│ More info      │ https://npmjs.com/advisories/577                             

It isn't critical but it isn't unpleasant.
Could you update elasticsearch library to latest version?

**Comment by Milad** [comment]
Working on it in #4!

**Comment by Milad** [comment]
Satisfied by #4 v2 will be released soon!
