### ISSUE TITLE
Support Elasticsearch authentication

### ISSUE THREAD

**Issue by DaveCLowe** [Milad/bunyan-elasticsearch-bulk#5]
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/auth-reference.html

Suggest env vars. I might submit a PR.

Thanks!

**Comment by Milad** [comment]
Thanks Dave

Please note that .env is only used for development and it's not necessary at all for this module to work in production.

A new and improved version is coming some time on the near future.

**Comment by Milad** [comment]
Satisfied by #4 v2 will be released soon!

You can put the authentication configurations in the same options object.
The object is passed as is to the ES client
